/*
Navicat Oracle Data Transfer
Oracle Client Version : 12.1.0.2.0

Source Server         : 172.18.11.27.demo
Source Server Version : 110200
Source Host           : 172.18.11.27:1521
Source Schema         : TRADE_GNNT

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2015-11-08 19:06:21
*/


-- ----------------------------
-- Table structure for F_B_CAPITALINFO
-- ----------------------------
DROP TABLE "TRADE_GNNT"."F_B_CAPITALINFO";
CREATE TABLE "TRADE_GNNT"."F_B_CAPITALINFO" (
"ID" NUMBER(12) NOT NULL ,
"FIRMID" VARCHAR2(32 BYTE) NOT NULL ,
"FUNID" VARCHAR2(100 BYTE) NULL ,
"BANKID" VARCHAR2(32 BYTE) NOT NULL ,
"DEBITID" VARCHAR2(32 BYTE) NOT NULL ,
"CREDITID" VARCHAR2(32 BYTE) NOT NULL ,
"TYPE" NUMBER(2) NOT NULL ,
"MONEY" NUMBER(12,2) NOT NULL ,
"OPERATOR" VARCHAR2(32 BYTE) NULL ,
"CREATETIME" DATE NOT NULL ,
"BANKTIME" DATE NULL ,
"STATUS" NUMBER(2) NOT NULL ,
"NOTE" VARCHAR2(128 BYTE) NULL ,
"ACTIONID" NUMBER(12) NOT NULL ,
"EXPRESS" NUMBER(1) DEFAULT 0  NULL ,
"BANKNAME" VARCHAR2(50 BYTE) NULL ,
"ACCOUNT" VARCHAR2(21 BYTE) NULL ,
"CREATEDATE" VARCHAR2(32 BYTE) NOT NULL ,
"FUNID2" VARCHAR2(100 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "TRADE_GNNT"."F_B_CAPITALINFO" IS '市场流水表';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."ID" IS '流水ID';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."FIRMID" IS '交易商代码';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."FUNID" IS '银行流水号';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."BANKID" IS '银行编号';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."DEBITID" IS '贷方代码';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."CREDITID" IS '借方代码';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."TYPE" IS '流水类型(0 入金,1 出金,2出入金手续费';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."MONEY" IS '流水金额';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."OPERATOR" IS '业务代码';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."CREATETIME" IS '创建时间';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."BANKTIME" IS '银行事件';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."STATUS" IS '状态(0 成功,1 失败,2 处理中,3 一次审核,4 二次审核,5 银行返回信息为空,6 银行返回市场流水号和市场保存流水号不一致,13 市场假银行出入金待审核状态)';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."NOTE" IS '备注信息';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."ACTIONID" IS '业务流水';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."EXPRESS" IS '是否加急';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."BANKNAME" IS '特殊加的(银行名称)';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."ACCOUNT" IS '特殊加的(银行账号)';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."CREATEDATE" IS '创建时间';
COMMENT ON COLUMN "TRADE_GNNT"."F_B_CAPITALINFO"."FUNID2" IS '流水2';

-- ----------------------------
-- Indexes structure for table F_B_CAPITALINFO
-- ----------------------------

-- ----------------------------
-- Checks structure for table F_B_CAPITALINFO
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."F_B_CAPITALINFO" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."F_B_CAPITALINFO" ADD CHECK ("FIRMID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."F_B_CAPITALINFO" ADD CHECK ("BANKID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."F_B_CAPITALINFO" ADD CHECK ("DEBITID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."F_B_CAPITALINFO" ADD CHECK ("CREDITID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."F_B_CAPITALINFO" ADD CHECK ("TYPE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."F_B_CAPITALINFO" ADD CHECK ("MONEY" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."F_B_CAPITALINFO" ADD CHECK ("CREATETIME" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."F_B_CAPITALINFO" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."F_B_CAPITALINFO" ADD CHECK ("ACTIONID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."F_B_CAPITALINFO" ADD CHECK ("CREATEDATE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."F_B_CAPITALINFO" ADD CHECK ("FUNID2" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table F_B_CAPITALINFO
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."F_B_CAPITALINFO" ADD PRIMARY KEY ("BANKID", "TYPE", "CREATEDATE", "FUNID2");
