/*
Navicat Oracle Data Transfer
Oracle Client Version : 12.1.0.2.0

Source Server         : 172.18.11.27.demo
Source Server Version : 110200
Source Host           : 172.18.11.27:1521
Source Schema         : TRADE_GNNT

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2015-11-08 17:35:42
*/


-- ----------------------------
-- Table structure for M_FIRM_APPLY
-- ----------------------------
DROP TABLE "TRADE_GNNT"."M_FIRM_APPLY";
CREATE TABLE "TRADE_GNNT"."M_FIRM_APPLY" (
"APPLYID" NUMBER(10) NOT NULL ,
"USERID" VARCHAR2(32 BYTE) NOT NULL ,
"PASSWORD" VARCHAR2(32 BYTE) NULL ,
"NAME" VARCHAR2(32 BYTE) NOT NULL ,
"FULLNAME" VARCHAR2(128 BYTE) NULL ,
"TYPE" NUMBER(2) NULL ,
"CONTACTMAN" VARCHAR2(32 BYTE) NULL ,
"CERTIFICATETYPE" NUMBER(2) NULL ,
"CERTIFICATENO" VARCHAR2(32 BYTE) NULL ,
"PHONE" VARCHAR2(32 BYTE) NULL ,
"MOBILE" NUMBER(12) NULL ,
"FAX" VARCHAR2(16 BYTE) NULL ,
"ADDRESS" VARCHAR2(128 BYTE) NULL ,
"POSTCODE" VARCHAR2(16 BYTE) NULL ,
"EMAIL" VARCHAR2(64 BYTE) NULL ,
"ZONECODE" VARCHAR2(16 BYTE) DEFAULT 'none'  NULL ,
"INDUSTRYCODE" VARCHAR2(16 BYTE) DEFAULT 'none'  NULL ,
"ORGANIZATIONCODE" VARCHAR2(9 BYTE) NULL ,
"CORPORATEREPRESENTATIVE" VARCHAR2(32 BYTE) NULL ,
"NOTE" VARCHAR2(1024 BYTE) NULL ,
"EXTENDDATA" VARCHAR2(4000 BYTE) NULL ,
"CREATETIME" DATE DEFAULT sysdate  NOT NULL ,
"MODIFYTIME" DATE NULL ,
"STATUS" NUMBER(1) DEFAULT 0  NOT NULL ,
"AUDITNOTE" VARCHAR2(256 BYTE) NULL ,
"BROKERID" VARCHAR2(32 BYTE) NULL ,
"PICTURE" BLOB NULL ,
"PICTURECS" BLOB NULL ,
"PICTUREOS" BLOB NULL ,
"YINGYEPIC" BLOB NULL ,
"SHUIWUPIC" BLOB NULL ,
"ZUZHIPIC" BLOB NULL ,
"KAIHUPIC" BLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "TRADE_GNNT"."M_FIRM_APPLY"."TYPE" IS '1：法人
2：代理
3：个人';
COMMENT ON COLUMN "TRADE_GNNT"."M_FIRM_APPLY"."STATUS" IS '0：待审核
1：审核通过
2：审核不通过';

-- ----------------------------
-- Indexes structure for table M_FIRM_APPLY
-- ----------------------------

-- ----------------------------
-- Checks structure for table M_FIRM_APPLY
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."M_FIRM_APPLY" ADD CHECK ("APPLYID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."M_FIRM_APPLY" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."M_FIRM_APPLY" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."M_FIRM_APPLY" ADD CHECK ("CREATETIME" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."M_FIRM_APPLY" ADD CHECK ("STATUS" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table M_FIRM_APPLY
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."M_FIRM_APPLY" ADD PRIMARY KEY ("APPLYID");
