/*
Navicat Oracle Data Transfer
Oracle Client Version : 12.1.0.2.0

Source Server         : 172.18.11.27.demo
Source Server Version : 110200
Source Host           : 172.18.11.27:1521
Source Schema         : TRADE_GNNT

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2015-11-08 19:09:09
*/


-- ----------------------------
-- Table structure for T_COMMODITY
-- ----------------------------
DROP TABLE "TRADE_GNNT"."T_COMMODITY";
CREATE TABLE "TRADE_GNNT"."T_COMMODITY" (
"COMMODITYID" VARCHAR2(16 BYTE) NOT NULL ,
"NAME" VARCHAR2(32 BYTE) NOT NULL ,
"SORTID" NUMBER(10) NOT NULL ,
"STATUS" NUMBER(2) NOT NULL ,
"CONTRACTFACTOR" NUMBER(12,2) NOT NULL ,
"MINPRICEMOVE" NUMBER(10,2) NOT NULL ,
"BREEDID" NUMBER(10) NOT NULL ,
"SPREADALGR" NUMBER(1) NOT NULL ,
"SPREADUPLMT" NUMBER(10,2) NOT NULL ,
"SPREADDOWNLMT" NUMBER(10,2) NOT NULL ,
"FEEALGR" NUMBER(1) NOT NULL ,
"FEERATE_B" NUMBER(15,9) NOT NULL ,
"FEERATE_S" NUMBER(15,9) NOT NULL ,
"MARGINALGR" NUMBER(1) NOT NULL ,
"MARGINRATE_B" NUMBER(10,4) DEFAULT 0  NOT NULL ,
"MARGINRATE_S" NUMBER(10,4) DEFAULT 0  NOT NULL ,
"MARKETDATE" DATE NULL ,
"SETTLEDATE" DATE NOT NULL ,
"SETTLEDATE1" DATE NULL ,
"MARGINITEM1" NUMBER(15,2) NULL ,
"SETTLEDATE2" DATE NULL ,
"MARGINITEM2" NUMBER(15,2) NULL ,
"SETTLEDATE3" DATE NULL ,
"MARGINITEM3" NUMBER(15,2) NULL ,
"SETTLEDATE4" DATE NULL ,
"MARGINITEM4" NUMBER(15,2) NULL ,
"LASTPRICE" NUMBER(10,2) NOT NULL ,
"MARGINITEM1_S" NUMBER(15,2) NULL ,
"MARGINITEM2_S" NUMBER(15,2) NULL ,
"MARGINITEM3_S" NUMBER(15,2) NULL ,
"MARGINITEM4_S" NUMBER(15,2) NULL ,
"MARGINASSURE_B" NUMBER(10,4) DEFAULT 0  NOT NULL ,
"MARGINASSURE_S" NUMBER(10,4) DEFAULT 0  NOT NULL ,
"MARGINITEMASSURE1" NUMBER(15,2) NULL ,
"MARGINITEMASSURE2" NUMBER(15,2) NULL ,
"MARGINITEMASSURE3" NUMBER(15,2) NULL ,
"MARGINITEMASSURE4" NUMBER(15,2) NULL ,
"MARGINITEMASSURE1_S" NUMBER(15,2) NULL ,
"MARGINITEMASSURE2_S" NUMBER(15,2) NULL ,
"MARGINITEMASSURE3_S" NUMBER(15,2) NULL ,
"MARGINITEMASSURE4_S" NUMBER(15,2) NULL ,
"TODAYCLOSEFEERATE_B" NUMBER(15,9) DEFAULT 0  NOT NULL ,
"TODAYCLOSEFEERATE_S" NUMBER(15,9) DEFAULT 0  NOT NULL ,
"HISTORYCLOSEFEERATE_B" NUMBER(15,9) DEFAULT 0  NOT NULL ,
"HISTORYCLOSEFEERATE_S" NUMBER(15,9) DEFAULT 0  NOT NULL ,
"LIMITCMDTYQTY" NUMBER(10) DEFAULT -1  NOT NULL ,
"SETTLEFEEALGR" NUMBER(1) NOT NULL ,
"SETTLEFEERATE_B" NUMBER(15,9) DEFAULT 0  NOT NULL ,
"SETTLEFEERATE_S" NUMBER(15,9) DEFAULT 0  NOT NULL ,
"FORCECLOSEFEEALGR" NUMBER(1) NOT NULL ,
"FORCECLOSEFEERATE_B" NUMBER(15,9) DEFAULT 0  NOT NULL ,
"FORCECLOSEFEERATE_S" NUMBER(15,9) DEFAULT 0  NOT NULL ,
"SETTLEMARGINALGR_B" NUMBER(1) NOT NULL ,
"SETTLEMARGINRATE_B" NUMBER(10,4) DEFAULT 0  NOT NULL ,
"SETTLEMARGINALGR_S" NUMBER(1) NOT NULL ,
"SETTLEMARGINRATE_S" NUMBER(10,4) DEFAULT 0  NOT NULL ,
"RESERVECOUNT" NUMBER(10) DEFAULT 0  NOT NULL ,
"ADDEDTAX" NUMBER(10,4) DEFAULT 0  NOT NULL ,
"MARGINPRICETYPE" NUMBER(1) DEFAULT 0  NOT NULL ,
"LOWESTSETTLEFEE" NUMBER(15,2) DEFAULT 0  NOT NULL ,
"FIRMCLEANQTY" NUMBER(10) DEFAULT -1  NOT NULL ,
"FIRMMAXHOLDQTY" NUMBER(10) DEFAULT -1  NOT NULL ,
"PAYOUTALGR" NUMBER(1) NOT NULL ,
"PAYOUTRATE" NUMBER(10,4) DEFAULT 0  NOT NULL ,
"ADDEDTAXFACTOR" NUMBER(13,10) DEFAULT 0  NOT NULL ,
"SETTLEDATE5" DATE NULL ,
"MARGINITEM5" NUMBER(15,2) NULL ,
"MARGINITEM5_S" NUMBER(15,2) NULL ,
"MARGINITEMASSURE5" NUMBER(15,2) NULL ,
"MARGINITEMASSURE5_S" NUMBER(15,2) NULL ,
"SETTLEPRICETYPE" NUMBER(2) DEFAULT 0  NOT NULL ,
"BEFOREDAYS" NUMBER(4) NULL ,
"SPECSETTLEPRICE" NUMBER(10,2) NULL ,
"ORDERPRIVILEGE_B" NUMBER(6) DEFAULT 101  NOT NULL ,
"ORDERPRIVILEGE_S" NUMBER(6) DEFAULT 101  NOT NULL ,
"FIRMMAXHOLDQTYALGR" NUMBER(1) DEFAULT 2  NOT NULL ,
"STARTPERCENTQTY" NUMBER(10) DEFAULT 0  NOT NULL ,
"MAXPERCENTLIMIT" NUMBER(7,4) DEFAULT 0  NOT NULL ,
"ONEMAXHOLDQTY" NUMBER(10) DEFAULT -1  NOT NULL ,
"MINQUANTITYMOVE" NUMBER(3) DEFAULT 1  NOT NULL ,
"DELAYRECOUPRATE" NUMBER(7,5) DEFAULT 0  NOT NULL ,
"SETTLEWAY" NUMBER(2) DEFAULT 0  NOT NULL ,
"DELAYFEEWAY" NUMBER(2) DEFAULT 1  NOT NULL ,
"MAXFEERATE" NUMBER(15,9) NULL ,
"MINSETTLEMOVEQTY" NUMBER(5) DEFAULT 1  NOT NULL ,
"STORERECOUPRATE" NUMBER(7,5) DEFAULT 0  NOT NULL ,
"MINSETTLEQTY" NUMBER(10) DEFAULT 1  NOT NULL ,
"DELAYRECOUPRATE_S" NUMBER(7,5) DEFAULT 0  NOT NULL ,
"AHEADSETTLEPRICETYPE" NUMBER(2) DEFAULT 0  NULL ,
"DELAYSETTLEPRICETYPE" NUMBER(2) DEFAULT 0  NULL ,
"SETTLEMARGINTYPE" NUMBER(2) DEFAULT 0  NULL ,
"BEFOREDAYS_M" NUMBER(2) DEFAULT 0  NULL ,
"SIDEHOLDLIMITQTY" NUMBER(10) DEFAULT -1  NULL ,
"HOLDDAYSLIMIT" NUMBER(1) DEFAULT 0  NOT NULL ,
"MAXHOLDPOSITIONDAY" NUMBER(10) NULL ,
"TAXINCLUSIVE" NUMBER(1) DEFAULT 1  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Indexes structure for table T_COMMODITY
-- ----------------------------

-- ----------------------------
-- Checks structure for table T_COMMODITY
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("COMMODITYID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("SORTID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("CONTRACTFACTOR" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("MINPRICEMOVE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("BREEDID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("SPREADALGR" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("SPREADUPLMT" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("SPREADDOWNLMT" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("FEEALGR" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("FEERATE_B" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("FEERATE_S" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("MARGINALGR" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("MARGINRATE_B" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("MARGINRATE_S" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("SETTLEDATE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("LASTPRICE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("MARGINASSURE_B" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("MARGINASSURE_S" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("TODAYCLOSEFEERATE_B" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("TODAYCLOSEFEERATE_S" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("HISTORYCLOSEFEERATE_B" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("HISTORYCLOSEFEERATE_S" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("LIMITCMDTYQTY" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("SETTLEFEEALGR" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("SETTLEFEERATE_B" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("SETTLEFEERATE_S" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("FORCECLOSEFEEALGR" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("FORCECLOSEFEERATE_B" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("FORCECLOSEFEERATE_S" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("SETTLEMARGINALGR_B" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("SETTLEMARGINRATE_B" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("SETTLEMARGINALGR_S" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("SETTLEMARGINRATE_S" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("RESERVECOUNT" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("ADDEDTAX" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("MARGINPRICETYPE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("LOWESTSETTLEFEE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("FIRMCLEANQTY" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("FIRMMAXHOLDQTY" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("PAYOUTALGR" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("PAYOUTRATE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("ADDEDTAXFACTOR" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("SETTLEPRICETYPE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("ORDERPRIVILEGE_B" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("ORDERPRIVILEGE_S" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("FIRMMAXHOLDQTYALGR" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("STARTPERCENTQTY" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("MAXPERCENTLIMIT" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("ONEMAXHOLDQTY" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("MINQUANTITYMOVE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("DELAYRECOUPRATE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("SETTLEWAY" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("DELAYFEEWAY" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("MINSETTLEMOVEQTY" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("STORERECOUPRATE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("MINSETTLEQTY" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("DELAYRECOUPRATE_S" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD CHECK ("HOLDDAYSLIMIT" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table T_COMMODITY
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."T_COMMODITY" ADD PRIMARY KEY ("COMMODITYID");
