/*
Navicat Oracle Data Transfer
Oracle Client Version : 12.1.0.2.0

Source Server         : 172.18.11.27.demo
Source Server Version : 110200
Source Host           : 172.18.11.27:1521
Source Schema         : TRADE_GNNT

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2015-11-08 19:11:41
*/


-- ----------------------------
-- Table structure for T_SETTLEMATCH
-- ----------------------------
DROP TABLE "TRADE_GNNT"."T_SETTLEMATCH";
CREATE TABLE "TRADE_GNNT"."T_SETTLEMATCH" (
"MATCHID" VARCHAR2(12 BYTE) NOT NULL ,
"COMMODITYID" VARCHAR2(16 BYTE) NOT NULL ,
"CONTRACTFACTOR" NUMBER(12,2) NOT NULL ,
"QUANTITY" NUMBER(10) NOT NULL ,
"HL_AMOUNT" NUMBER(15,2) DEFAULT 0  NOT NULL ,
"STATUS" NUMBER(2) DEFAULT 0  NOT NULL ,
"RESULT" NUMBER(1) NOT NULL ,
"SETTLETYPE" NUMBER(2) NOT NULL ,
"FIRMID_B" VARCHAR2(32 BYTE) NOT NULL ,
"BUYPRICE" NUMBER(15,6) NOT NULL ,
"BUYPAYOUT_REF" NUMBER(15,2) DEFAULT 0  NOT NULL ,
"BUYPAYOUT" NUMBER(15,2) DEFAULT 0  NOT NULL ,
"BUYMARGIN" NUMBER(15,2) DEFAULT 0  NOT NULL ,
"TAKEPENALTY_B" NUMBER(15,2) DEFAULT 0  NOT NULL ,
"PAYPENALTY_B" NUMBER(15,2) DEFAULT 0  NOT NULL ,
"SETTLEPL_B" NUMBER(15,2) DEFAULT 0  NOT NULL ,
"FIRMID_S" VARCHAR2(32 BYTE) NOT NULL ,
"SELLPRICE" NUMBER(15,6) NOT NULL ,
"SELLINCOME_REF" NUMBER(15,2) DEFAULT 0  NOT NULL ,
"SELLINCOME" NUMBER(15,2) DEFAULT 0  NOT NULL ,
"SELLMARGIN" NUMBER(15,2) DEFAULT 0  NOT NULL ,
"TAKEPENALTY_S" NUMBER(15,2) DEFAULT 0  NOT NULL ,
"PAYPENALTY_S" NUMBER(15,2) DEFAULT 0  NOT NULL ,
"SETTLEPL_S" NUMBER(15,2) DEFAULT 0  NOT NULL ,
"CREATETIME" DATE NOT NULL ,
"MODIFYTIME" DATE NOT NULL ,
"SETTLEDATE" DATE NOT NULL ,
"MODIFIER" VARCHAR2(64 BYTE) NULL ,
"ISTRANSFER" NUMBER(2) DEFAULT 0  NOT NULL ,
"BUYTAX" NUMBER(15,2) DEFAULT 0  NULL ,
"TAXINCLUESIVE" NUMBER(1) DEFAULT 0  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "TRADE_GNNT"."T_SETTLEMATCH"."BUYTAX" IS '交收税费';
COMMENT ON COLUMN "TRADE_GNNT"."T_SETTLEMATCH"."TAXINCLUESIVE" IS '商品是否含税,0默认含税，1为不含税';

-- ----------------------------
-- Indexes structure for table T_SETTLEMATCH
-- ----------------------------

-- ----------------------------
-- Checks structure for table T_SETTLEMATCH
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("MATCHID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("COMMODITYID" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("CONTRACTFACTOR" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("QUANTITY" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("HL_AMOUNT" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("STATUS" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("RESULT" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("SETTLETYPE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("FIRMID_B" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("BUYPRICE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("BUYPAYOUT_REF" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("BUYPAYOUT" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("BUYMARGIN" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("TAKEPENALTY_B" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("PAYPENALTY_B" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("SETTLEPL_B" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("FIRMID_S" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("SELLPRICE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("SELLINCOME_REF" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("SELLINCOME" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("SELLMARGIN" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("TAKEPENALTY_S" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("PAYPENALTY_S" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("SETTLEPL_S" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("CREATETIME" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("MODIFYTIME" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("SETTLEDATE" IS NOT NULL);
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD CHECK ("ISTRANSFER" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table T_SETTLEMATCH
-- ----------------------------
ALTER TABLE "TRADE_GNNT"."T_SETTLEMATCH" ADD PRIMARY KEY ("MATCHID");
